apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: webserver
spec:
  containers:
    - name: mycontainer
      image: nginx:latest
      resources:
        requests:
          memory: "128Mi" # 128Mi = 128 mebibytes
          cpu: "200m" # 200m = 200 milliCPUs (1/5 CPU)
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
